server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://120.48.66.99:3306/test?characterEncoding=utf-8
    username: user1
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path:
      - classpath:/templates/
